### PR TITLE
V2.1.6

### PR DESCRIPTION
**Pull request by grgicmatej**
Done:
- Added missing return types

### CODE REVIEW

**Comment by gmaccario** [comment]
Hi @grgicmatej @KondukterCRO is there an estimated time on when these changes will be released? Those change would be very useful in my project to avoid the following deprecation message: 

image

**Comment by grgicmatej** [comment]
@gmaccario I will check this out next week and get back to you. Sounds good?

**Comment by gmaccario** [comment]
@grgicmatej perfect, thank you!

**Review by KondukterCRO — APPROVED** [review]

**Comment by KondukterCRO** [comment]
@gmaccario merged :)

**Comment by gmaccario** [comment]
Thank you guys!

**Comment by gmaccario** [comment]
Hi @grgicmatej @KondukterCRO I am still having the issue, no matter if I run composer or if I download manually the release v2.1.6, I do not see the returning type. Can you please have a double-check?
image
image
image

**Comment by grgicmatej** [comment]
@gmaccario Hi! Please use v2.1.8: https://packagist.org/packages/undabot/json-api-core#v2.1.8

**Pull request merged**
